variable "cluster_name" {
  type        = string
  description = "(Required) The name that will be given to the kafka cluster and it's namespace"
}
variable "replicas" {
  type        = number
  description = "(Optional) Number of zookeepers brokers to be created."
  default     = 3
}

variable "root_log_level" {
  type        = string
  description = <<EOF
  (Optional) log level value must be one of:
  ```
  [INFO, ERROR, WARN, TRACE, DEBUG, FATAL, OFF]
  ```
  EOF
  default     = "INFO"
}

variable "resources" {
  type        = map(string)
  description = "(Optional) Resource requests/limit (CPU & Memory) to specify the maximum resources that can be consumed."
  default = {
    requested_memory = "5Gi"
    requested_cpu    = "1"
    limit_cpu        = "2"
    limit_memory     = "6Gi"
  }
}

variable "jvm" {
  type        = map(string)
  description = <<EOT
  Confiuration of JVM options for maximum and minimum memory allocation:
  -Xms = Minimum initial allocation heap size when the JVM starts.
  -Xmx = Maximum heap size.
  EOT
  default = {
    xms = "4096m"
    xmx = "4096m"
  }
}

variable "pod_annotations" {
  type        = map(string)
  description = "(Optional) Additional attached annotations to the Kafka brokers pods."
  default = {
    "ad.datadoghq.com/zookeeper.check_names" : "['zk']"
    "ad.datadoghq.com/zookeeper.init_configs" : "[{}]"
    "ad.datadoghq.com/zookeeper.instances" : "[{ 'host' : '%%host%%', 'port' : '2181' }]"
    "ad.datadoghq.com/zookeeper.logs" : "[{ 'source' : 'zookeeper', 'service' : 'zookeeper' }]"
  }
}

variable "affinity" {
  type        = map(string)
  description = "(Required) Labels and Taints that are used on dedicated Zookeeper nodes."
}

variable "service_annotations" {
  type        = map(string)
  description = <<EOT
  (Optional) Attached annotations to the Zookeeper Service.
  In addition to the default value , consul service_name is generated by:
  `"consul.hashicorp.com/service-name" : "strimzi-zookeeper-<cluster_name>"`
  it will be generated from the cluster-name and will be auto implemented.
  in order to override that value: 
  ```
  service_annotations = 
  { 
  consul.hashicorp.com/service-name: "<SERVICE_NAME>"
  }
  EOT
  default = {
    "consul.hashicorp.com/service-sync" : "true"
  }
}

variable "storage" {
  type        = map(string)
  description = "(Required) Zookeeper Brokers persistence storage configuration."
}

variable "configmap_name" {
  description = "(Required) ConfigMap deployment name that holds Cruise Control Metrics."
  type        = string
}

variable "configmap_key" {
  description = "(Required) ConfigMap deployment key that holds Cruise Control Metrics."
  type        = string
}
